services:
  authenticationdb:
    container_name: authenticationdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1439:1433"

  conferencemanagementdb:
    container_name: conferencemanagementdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1440:1433"
 
  registrationdb:
    container_name: registrationdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1441:1433"

  notificationdb:
    container_name: notificationdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1442:1433"

  messagebroker:
    container_name: messagebroker
    hostname: confy-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=authenticationdb;Database=AuthenticationDb;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
      - Jwt__Issuer=AuthService
      - Jwt__Audience=Microservices
      - Jwt__Key=YourSuperVeryVeryLongSecretKeyHere
      - MessageBroker__Host=amqp://confy-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - authenticationdb
      - messagebroker
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  conferencemanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=conferencemanagementdb;Database=ConferenceManagementDb;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
      - Jwt__Authority=http://authentication.api:8080
      - Jwt__Audience=Microservices
      - Jwt__Key=YourSuperVeryVeryLongSecretKeyHere
      - MessageBroker__Host=amqp://confy-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - conferencemanagementdb
      - messagebroker
      - authentication.api
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  registration.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=registrationdb;Database=RegistrationDb;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
      - Jwt__Authority=http://authentication.api:8080
      - Jwt__Audience=Microservices
      - Jwt__Key=YourSuperVeryVeryLongSecretKeyHere
      - MessageBroker__Host=amqp://confy-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - registrationdb
      - messagebroker
      - authentication.api
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=notificationdb;Database=NotificationDb;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
      - Jwt__Authority=http://authentication.api:8080
      - Jwt__Audience=Microservices
      - Jwt__Key=YourSuperVeryVeryLongSecretKeyHere
      - MessageBroker__Host=amqp://confy-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - notificationdb
      - messagebroker
      - authentication.api
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
