services:
  authenticationdb:
    image: mcr.microsoft.com/mssql/server

  conferencemanagementdb:
    image: mcr.microsoft.com/mssql/server

  notificationdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Authentication/Authentication.API/Dockerfile

  conferencemanagement.api:
    image: ${DOCKER_REGISTRY-}conferencemanagementapi
    build:
      context: .
      dockerfile: Services/ConferenceManagement/ConferenceManagement.API/Dockerfile

